const icon = (className, extraClass = 'h-5 w-5') => [
    '<i class="', className, ' ', extraClass, ' inline-flex shrink-0 items-center justify-center" aria-hidden="true"></i>'
].join('');

const icons = {
    menu: icon('fa-solid fa-bars'),
    search: icon('fa-solid fa-magnifying-glass'),
    searchField: icon('fa-solid fa-magnifying-glass', 'pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2'),
    bell: icon('fa-solid fa-bell'),
    help: icon('fa-regular fa-circle-question'),
    user: icon('fa-solid fa-user'),
    chevron: icon('fa-solid fa-chevron-down', 'h-4 w-4'),
    settings: icon('fa-solid fa-gear'),
    logout: icon('fa-solid fa-right-from-bracket'),
    closeSearch: icon('fa-solid fa-xmark')
};

export function Navbar(options = {}) {
    const {
        title = 'IT Administrator Dashboard',
        subtitle = 'Integration control center'
    } = options;

    return [
        '<header id="admin-navbar" class="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur" aria-label="Administration header">',
            '<div class="relative mx-auto flex min-h-[4.75rem] max-w-[1600px] min-w-0 items-center gap-2 px-4 py-3 sm:gap-3 sm:px-6 lg:px-8">',
                '<div class="flex min-w-0 flex-1 items-center gap-2 sm:gap-3" data-navbar-normal-content>',
                '<button type="button" class="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600 shadow-sm transition hover:border-slate-300 hover:text-au-navy lg:hidden" data-sidebar-open aria-controls="admin-sidebar" aria-expanded="false" aria-label="Open navigation menu">',
                    icons.menu,
                '</button>',
                '<div class="min-w-0 flex-1 xl:max-w-[18rem] 2xl:max-w-[22rem]">',
                    '<p class="truncate text-sm font-bold text-au-navy sm:text-base">', title, '</p>',
                    '<p class="mt-0.5 hidden truncate text-[11px] font-medium text-slate-500 sm:block">', subtitle, '</p>',
                '</div>',
                '<div class="hidden min-w-0 flex-1 items-center justify-end gap-3 xl:flex" data-search-shell>',
                    '<label class="relative min-w-0 w-full max-w-[22rem] flex-1">',
                        '<span class="sr-only">Search dashboard</span>',
                        icons.searchField,
                        '<input id="global-search" type="search" placeholder="Search dashboard" aria-label="Search dashboard" aria-keyshortcuts="Control+K Meta+K" class="h-11 min-w-0 w-full rounded-xl border border-slate-200 bg-slate-50 pl-11 pr-16 text-xs font-medium text-slate-700 outline-none transition placeholder:text-slate-400 hover:border-slate-300 focus:border-blue-300 focus:ring-4 focus:ring-blue-100" />',
                        '<span class="pointer-events-none absolute right-3 top-1/2 hidden -translate-y-1/2 rounded-md border border-slate-200 bg-white px-1.5 py-0.5 text-[9px] font-bold text-slate-400 2xl:block" aria-hidden="true">Ctrl K</span>',
                    '</label>',
                    '<div class="hidden items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 px-3 py-2 2xl:flex">',
                        '<span class="status-dot status-dot-online"></span>',
                        '<span class="text-[10px] font-bold uppercase tracking-[0.08em] text-emerald-800">System Status</span>',
                        '<span class="text-xs font-extrabold text-emerald-700">5 / 6 Online</span>',
                    '</div>',
                '</div>',
                '<div class="flex shrink-0 items-center gap-1.5 sm:gap-2">',
                    '<button type="button" class="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-slate-500 transition hover:bg-slate-100 hover:text-au-navy xl:hidden" data-search-trigger aria-controls="mobile-search-mode" aria-expanded="false" aria-label="Open search">',
                        icons.search,
                    '</button>',
                    '<div class="flex items-center gap-1.5 rounded-xl border border-emerald-100 bg-emerald-50 px-2.5 py-2 2xl:hidden">',
                        '<span class="status-dot status-dot-online"></span>',
                        '<span class="text-[10px] font-extrabold text-emerald-700">5 / 6</span>',
                    '</div>',
                    '<button type="button" class="relative grid h-10 w-10 place-items-center rounded-xl text-slate-500 transition hover:bg-slate-100 hover:text-au-navy" data-ui-action="notifications" aria-label="View notifications">',
                        icons.bell,
                        '<span class="absolute right-2 top-1.5 grid h-4 min-w-4 place-items-center rounded-full bg-au-red px-1 text-[9px] font-extrabold text-white">3</span>',
                    '</button>',
                    '<button type="button" class="hidden h-10 w-10 place-items-center rounded-xl text-slate-500 transition hover:bg-slate-100 hover:text-au-navy sm:grid" data-ui-action="help" aria-label="Open help">',
                        icons.help,
                    '</button>',
                    '<div class="relative">',
                        '<button type="button" class="flex h-10 items-center gap-2 rounded-xl px-1.5 text-left transition hover:bg-slate-100" id="profile-button" data-profile-button aria-expanded="false" aria-controls="profile-menu">',
                            '<span class="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-blue-50 text-au-blue">',
                                icons.user,
                            '</span>',
                            '<span class="hidden min-w-0 sm:block">',
                                '<span class="block max-w-28 truncate text-xs font-bold text-slate-700">Administrator</span>',
                                '<span class="mt-0.5 block text-[10px] font-medium text-slate-400">IT Administrator</span>',
                            '</span>',
                            icons.chevron,
                        '</button>',
                        '<div id="profile-menu" class="absolute right-0 top-12 hidden w-56 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl shadow-slate-900/10" data-profile-menu hidden>',
                            '<div class="border-b border-slate-100 px-3 py-2.5">',
                                '<p class="text-xs font-bold text-slate-800">Administrator account</p>',
                                '<p class="mt-1 text-[11px] text-slate-500">AU-JSC integration access</p>',
                            '</div>',
                            '<button type="button" class="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-semibold text-slate-600 transition hover:bg-slate-50 hover:text-au-navy" data-ui-action="account settings">',
                                icons.settings,
                                '<span>Account settings</span>',
                            '</button>',
                            '<button type="button" class="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-semibold text-slate-600 transition hover:bg-slate-50 hover:text-au-navy" data-ui-action="logout">',
                                icons.logout,
                                '<span>Logout</span>',
                            '</button>',
                        '</div>',
                    '</div>',
                '</div>',
                '</div>',
                '<div id="mobile-search-mode" class="hidden min-w-0 flex-1 items-center" data-mobile-search-mode>',
                    '<div class="relative min-w-0 flex-1">',
                        '<label class="block">',
                            '<span class="sr-only">Search dashboard</span>',
                            icons.searchField,
                            '<input id="mobile-dashboard-search" type="search" placeholder="Search dashboard" aria-label="Search dashboard" class="h-10 min-w-0 w-full rounded-xl border border-slate-200 bg-slate-50 pl-11 pr-12 text-xs font-medium text-slate-700 outline-none transition placeholder:text-slate-400 hover:border-slate-300 focus:border-blue-300 focus:ring-4 focus:ring-blue-100" />',
                        '</label>',
                        '<button type="button" id="close-mobile-search" class="absolute right-2 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-lg text-slate-500 transition hover:bg-slate-100 hover:text-au-navy" aria-label="Close search">',
                            icons.closeSearch,
                        '</button>',
                    '</div>',
                '</div>',
            '</div>',
        '</header>'
    ].join('');
}
