import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faAddressBook,
  faArrowRight,
  faArrowsRotate,
  faBars,
  faBell,
  faBuilding,
  faCalculator,
  faCalendarDays,
  faChartLine,
  faCheck,
  faChevronDown,
  faCircleInfo,
  faCircleQuestion,
  faClipboardList,
  faClock,
  faCommentDots,
  faEnvelope,
  faFileLines,
  faFingerprint,
  faFilter,
  faGear,
  faHand,
  faKey,
  faLayerGroup,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMoneyBillWave,
  faPhone,
  faQrcode,
  faRightFromBracket,
  faShieldHalved,
  faSun,
  faTableCellsLarge,
  faTriangleExclamation,
  faUser,
  faUserShield,
  faUsers,
  faWaveSquare,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

import type { IconName } from "@/types/ui";

const icons: Record<IconName, IconDefinition> = {
  dashboard: faTableCellsLarge,
  monitoring: faChartLine,
  hrps: faAddressBook,
  bundy: faFingerprint,
  qr: faQrcode,
  unified: faLayerGroup,
  payroll: faMoneyBillWave,
  accounting: faCalculator,
  errors: faTriangleExclamation,
  users: faUsers,
  roles: faUserShield,
  audit: faClipboardList,
  settings: faGear,
  menu: faBars,
  search: faMagnifyingGlass,
  bell: faBell,
  help: faCircleQuestion,
  user: faUser,
  chevron: faChevronDown,
  logout: faRightFromBracket,
  close: faXmark,
  calendar: faCalendarDays,
  check: faCheck,
  clock: faClock,
  warning: faTriangleExclamation,
  info: faCircleInfo,
  refresh: faArrowsRotate,
  arrow: faArrowRight,
  filter: faFilter,
  lock: faLock,
  key: faKey,
  support: faEnvelope,
  sun: faSun,
  hand: faHand,
  file: faFileLines,
  layers: faLayerGroup,
  shield: faShieldHalved,
  activity: faWaveSquare,
  building: faBuilding,
  phone: faPhone,
  location: faLocationDot,
  comment: faCommentDots,
};

type IconProps = {
  name: IconName;
  className?: string;
};

export function Icon({ name, className = "" }: IconProps) {
  return <FontAwesomeIcon className={`ui-icon ${className}`.trim()} icon={icons[name]} aria-hidden="true" />;
}
